export const mySkills = [
  { title: "Python", icon: "python" },
  { title: "C++", icon: "cplusplus" },
  { title: "C", icon: "c" },
  { title: "JavaScript", icon: "javascript" },
  { title: "TypeScript", icon: "typescript" },
  { title: "Java", icon: "java" },
  { title: "R", icon: "r" },
  { title: "HTML", icon: "html" },
  { title: "CSS", icon: "css" },
  { title: "NextJS", icon: "nextjs" },
  { title: "ReactJS", icon: "react" },
  { title: "Tailwind CSS", icon: "tailwind" },
  { title: "Framer Motion", icon: "framer" },
  { title: "Claude AI", icon: "anthropic" },
  { title: "Hugging Face", icon: "huggingface" },
  { title: "Scikit-Learn", icon: "scikitlearn" },
  { title: "Docker", icon: "docker" },
  { title: "Git", icon: "git" },
  { title: "GitHub", icon: "github" },
  { title: "Vercel", icon: "vercel" },
  { title: "NodeJS", icon: "node" },
  { title: "MongoDB", icon: "mongodb" },
];